<?php

namespace HncProjectBundle\Repository;

/**
 * ColourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColourRepository extends \Doctrine\ORM\EntityRepository
{
}
