<?php

namespace HncProjectBundle\Repository;

/**
 * user_settingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_settingsRepository extends \Doctrine\ORM\EntityRepository
{
}
